dist: trusty
sudo: required
language: go
go:
- 1.8
env:
  global:
  - AMQP_URL="amqp://guest:guest@localhost:5672/"
matrix:
  fast_finish: true
services:
  - rabbitmq
before_install:
  - go get github.com/kardianos/govendor
  - go get github.com/onsi/ginkgo/ginkgo
install:
  - wget -O toxiproxy-2.1.3.deb https://github.com/Shopify/toxiproxy/releases/download/v2.1.3/toxiproxy_2.1.3_amd64.deb
  - sudo dpkg -i toxiproxy-2.1.3.deb
  - govendor sync
  - toxiproxy-server &
script:
  - ginkgo
